version: '3.7'
services:
  catraca:
    #image: çççççç
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8083
    ports:
    - "8083:8083"
    restart: unless-stopped

#    networks:
#      - catraca_net
#
#
#networks:
#  catraca_net: